### PR TITLE
Dashboard Page Complete with Responsive and Grid & List view

### PR DESCRIPTION
**Pull request by TanvirMahin24**
image
image

### CODE REVIEW

**Comment by NayeemH** [comment]
Responsive tao sathe sathe kore felish

**Review by NayeemH — CHANGES_REQUESTED** [review]
Make responsive ....

**Review by NayeemH — CHANGES_REQUESTED** [review]
Add "Favorite" text to the top section where all favorite projects will be shown.

**Comment by TanvirMahin24** [comment]
Responsive done @NayeemH vai
image

**Comment by NayeemH** [comment]
Add favorite text

**Comment by TanvirMahin24** [comment]
Video te Favorite text cilo na vai

**Comment by NayeemH** [comment]
Tao de tui

**Comment by TanvirMahin24** [comment]
@NayeemH  vai done

image

**Pull request merged**
